### PR TITLE
Added a file path into an error message while reading a file fixes #405

### PR DESCRIPTION
**Pull request by LukasRychtecky**
Hi,

I've added a file name into an error message and I think it'd be helpful.

screen shot 2018-03-01 at 16 45 50

### CODE REVIEW

**Comment by LukasRychtecky** [comment]
@jonase Do you have any comments?

**Comment by arrdem** [comment]
@danielcompton any comment? I'm not opposed, fixing the redundant `println format` to `printf` is easy enough.

**Comment by danielcompton** [comment]
Seems reasonable to me.

**Comment by danielcompton** [comment]
`printf` change sounds good. Happy for you to do, or I'll get to it eventually.

**Comment by LukasRychtecky** [comment]
Thx!

**Pull request merged**
