### PR TITLE
remove the threading rules

### PR DESCRIPTION
**Pull request by yogsototh**
I generally use the thread macro to make the code more readable when the functions and values aren't small.

``` clojure
(-> (something a bit long)
     (another-long s-expr with parameters))
```

is easier to read than

``` clojure
(another-long (something a bit long) s-expr with parameters)
```

and so I would prefer not to keep this simplification rule.

### CODE REVIEW

**Comment by joelittlejohn** [comment]
I'd love to see this one merged as I completely agree that there are many situations in which the threaded version is more readable, even when there is only one function invoked in the thread.

@jonase Any objections to merging this?

**Comment by danielcompton** [comment]
I'm planning to make rules selectable, so you can pick or remove your own ones that you like.

**Comment by joelittlejohn** [comment]
@danielcompton That would certainly be nice. Support for a kibit definition that can sit inside a project would be great. I'd still suggest that these two threading rules should be _off_ by default :)

**Comment by joelittlejohn** [comment]
Any more support for turning these two rules off by default (turn them off in the core right now)?

**Pull request closed without merging**
