### PR TITLE
Allows tools to also use the end of a range besides just the start

### PR DESCRIPTION
**Pull request by svdo**
I'm writing an editor plugin that will allow replacing of Kibit suggestions as you type, one by one. In order to do that, I need to tell the editor what range (start line/col to end line/col) can be replaced. Kibit internally has that information, but not in a way that I can access it from the API (unless I missed something of course). 

This pull request exposes the `:end-line` and `:end-column` meta so that I can use it in my editor plugin.

(Note that I'm suing `identity` as a reporter so that I get the data structure for further processing in my plugin.)

I would be super-greatful if this can be merged and deployed, so that I don't have to publish my own fork of Kibit, which I'd rather avoid. Many thanks!

### CODE REVIEW

**Comment by svdo** [comment]
Hi! Can I interest someone in merging this? @danielcompton or @carrete maybe? Thanks!! :)

**Comment by carrete** [comment]
Sorry @svdo, I don't have commit permissions.

**Comment by danielcompton** [comment]
Sorry for the delay! This is merged now. I'll try and get a release out soon.

**Comment by svdo** [comment]
No worries, thank you!

**Comment by NoahTheDuke** [comment]
Released in 0.1.10.

**Pull request merged**
