### PR TITLE
fns * and + with one argument is identity fn

### PR DESCRIPTION
**Pull request by erdos**
that is (* ?x) == ?x (#'+ is similar)

### CODE REVIEW

**Comment by erdos** [comment]
done

**Comment by BenjaminVanRyseghem** [comment]
Sorry but the build failed :/

**Comment by danielcompton** [comment]
The build was already broken :/

**Comment by danielcompton** [comment]
I like the thinking behind this one, but it's going to interfere with fairly idiomatic Clojure like:

```clj
(-> (:rebar {:rebar 23})
    (* 2))
```

Kibit doesn't expand macros so it can quite easily make breaking suggestions like in this case. I also have a feeling that there would be other valid and idiomatic macros that this would suggest are wrong. At the moment I think the potential annoyance of seeing suggestions for valid and idiomatic Clojure code outweighs the relatively minor likelihood of someone accidentally writing `(* 5)` when they should really be writing `5`.

If kibit ever expands macro's I'd love to include this :+1:. Thanks for your contribution and sorry for the belated response.

**Pull request closed without merging**
