### PR TITLE
Kibit cannot parse ns with string requires

### PR DESCRIPTION
**Pull request by marksto**
This is a minor enhancement that fixes: #242

### CODE REVIEW

**Comment by marksto** [comment]
@danielcompton, hello! Please, approve.

**Comment by marksto** [comment]
Hello again! Can I interest someone in merging this? @danielcompton or @jonase maybe? Thanks in advance!

**Comment by danielcompton** [comment]
Sorry for the delay!

**Comment by danielcompton** [comment]
Would you be able to add a test for this too in a followup PR?

**Comment by marksto** [comment]
Um, sure!.. Sorry for the lack of one in the original PR.

**Pull request merged**
